// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aumzleiqvdkdjxxvaest.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1bXpsZWlxdmRrZGp4eHZhZXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNTIxNTksImV4cCI6MjA2MjYyODE1OX0.OhQh8trlkyKgSAuNjZENJz2385iK3ytQ7XmPB0jo78I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);